apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: deferred-deeplink-server
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/deferred-deeplink-demo/cloud-run-source-deploy/deferred-deeplink-server
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
profiles:
  - name: sandbox
    manifests:
      rawYaml:
        - k8s/sandbox-deployment.yaml
    deploy:
      kubectl: {}
